#!/bin/bash

echo "unix:///var/run/convoy/convoy-ebs.sock" > /etc/docker/plugins/convoy-ebs.spec

convoy -s /host/var/run/convoy/convoy-ebs.sock \
  daemon \
  --mnt-ns /host/proc/$PPID/ns/mnt \
  --drivers ebs \
  $@
