#!/bin/bash

echo "unix:///var/run/convoy/convoy-ebs.sock" > /etc/docker/plugins/convoy-ebs.spec

echo "Will enter namesapce for $(ps --no-header --pid $$ -o ppid)"

convoy -s /host/var/run/convoy/convoy-ebs.sock \
  daemon \
  --mnt-ns /host/proc/$(ps --no-header --pid $$ -o ppid)/ns/mnt \
  --drivers ebs \
  $@
